spring:
  application:
    name: "assignment"
  datasource:
    url: "jdbc:mysql://localhost:3306/assignment"
    username: "root"
    password: "12345677"
    driver-class-name: com.mysql.cj.jdbc.Driver

